[package]
name = "k8s-api-conversion"
description = "Version conversion logic for Kubernetes API types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
k8s-api = { workspace = true }
k8s-apimachinery = { workspace = true }
thiserror = { workspace = true }
